FROM apache/airflow:2.10.5-python3.12

USER root

RUN rm -f /etc/apt/sources.list.d/mysql.list && \
    rm -f /etc/apt/sources.list.d/mysql-community.list && \
    apt-get update && \
    apt-get install -y openjdk-17-jdk && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir \
    pyspark==4.2.0 \
    pandas \
    pyarrow \
    requests \
    boto3==1.43.85