services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      DATA_STORAGE: ${DATA_STORAGE:-local}
      S3_BUCKET: ${S3_BUCKET:-f1-data-platform-fabio}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - f1-data-volume:/opt/airflow/project/data

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Fabio
      --lastname Munhoz
      --role Admin
      --email admin@example.com
      "

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: "300"
      AIRFLOW__WEBSERVER__SECRET_KEY: "f1-data-platform-airflow-secret-key"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo

      DATA_STORAGE: ${DATA_STORAGE:-local}
      S3_BUCKET: ${S3_BUCKET:-f1-data-platform-fabio}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - f1-data-volume:/opt/airflow/project/data

    command: webserver

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    depends_on:
      - postgres

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "f1-data-platform-airflow-secret-key"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo

      DATA_STORAGE: ${DATA_STORAGE:-local}
      S3_BUCKET: ${S3_BUCKET:-f1-data-platform-fabio}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
      - f1-data-volume:/opt/airflow/project/data

    command: scheduler


volumes:
  postgres-db-volume:
  f1-data-volume: